# Generated by Django 4.0.3 on 2022-04-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainAddress',
            fields=[
                ('address', models.CharField(default='0x0', max_length=42, primary_key=True, serialize=False)),
                ('ens', models.CharField(max_length=200, null=True)),
                ('contract_name', models.CharField(max_length=200, null=True)),
                ('contract_abi', models.JSONField(default=dict, null=True)),
            ],
            options={
                'db_table': 'blockchain_addresses',
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('transaction_id', models.CharField(default='0.0', max_length=20, primary_key=True, serialize=False)),
                ('transaction_hash', models.CharField(max_length=66, null=True)),
                ('block_number', models.PositiveIntegerField()),
                ('value', models.FloatField()),
                ('articulated_trace', models.JSONField(default=dict, null=True)),
                ('contracts_created', models.ManyToManyField(related_name='created_by_transaction', to='database.blockchainaddress')),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='database.blockchainaddress')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='database.blockchainaddress')),
            ],
            options={
                'db_table': 'blockchain_transactions',
            },
        ),
        migrations.CreateModel(
            name='DaoFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='not specified', max_length=200)),
                ('website', models.URLField(null=True)),
                ('github', models.URLField(null=True)),
            ],
            options={
                'db_table': 'dao_frameworks',
            },
        ),
        migrations.CreateModel(
            name='DaoFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='not specified', max_length=200)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to_factory', to='database.blockchainaddress')),
                ('dao_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='database.daoframework')),
                ('related_transactions', models.ManyToManyField(related_name='related_to_factory', to='database.blockchaintransaction')),
            ],
            options={
                'db_table': 'dao_factories',
            },
        ),
        migrations.CreateModel(
            name='Dao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('website', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('deepdao', models.URLField(null=True)),
                ('boardroom', models.URLField(null=True)),
                ('governance_addresses', models.ManyToManyField(related_name='belongs_to_dao', to='database.blockchainaddress')),
            ],
            options={
                'db_table': 'daos',
            },
        ),
    ]
