# Generated by Django 4.0.3 on 2022-03-29 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('ens', models.CharField(max_length=200, null=True)),
                ('url', models.URLField(null=True)),
            ],
            options={
                'db_table': 'blockchain_addresses',
            },
        ),
        migrations.CreateModel(
            name='DaoFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactoryContract',
            fields=[
                ('blockchainaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.blockchainaddress')),
                ('name', models.CharField(max_length=200, null=True)),
                ('dao_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='database.daoframework')),
            ],
            options={
                'db_table': 'factory_contracts',
            },
            bases=('database.blockchainaddress',),
        ),
        migrations.CreateModel(
            name='Dao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('website', models.URLField()),
                ('twitter', models.URLField()),
                ('governance_addresses', models.ManyToManyField(related_name='belongs_to', to='database.blockchainaddress')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryContractTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('transaction_hash', models.CharField(max_length=200, null=True)),
                ('block', models.PositiveIntegerField()),
                ('articulated_trace', models.JSONField(default=dict)),
                ('contracts_created', models.ManyToManyField(related_name='created_by_transaction', to='database.blockchainaddress')),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_from', related_query_name='%(app_label)s_%(class)ss_from', to='database.blockchainaddress')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_to', related_query_name='%(app_label)s_%(class)ss_to', to='database.blockchainaddress')),
                ('factory_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='database.factorycontract')),
            ],
            options={
                'db_table': 'factory_contract_transactions',
            },
        ),
    ]
