# Generated by Django 4.0.3 on 2022-03-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchainaddress',
            name='id',
        ),
        migrations.RemoveField(
            model_name='factorycontracttransaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='blockchainaddress',
            name='address',
            field=models.CharField(default='0x0', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factorycontracttransaction',
            name='transaction_id',
            field=models.CharField(default='0.0', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='dao',
            table='daos',
        ),
        migrations.AlterModelTable(
            name='daoframework',
            table='dao_frameworks',
        ),
    ]
