# Generated by Django 4.0.3 on 2022-04-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daofactory',
            old_name='contract',
            new_name='contract_address',
        ),
    ]
