# Generated by Django 4.0.3 on 2022-04-19 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_blockchainaddress_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('transaction_id', models.CharField(default='0.0', max_length=200, primary_key=True, serialize=False)),
                ('transaction_hash', models.CharField(max_length=200, null=True)),
                ('block', models.PositiveIntegerField()),
                ('value', models.FloatField()),
                ('articulated_trace', models.JSONField(default=dict)),
                ('contracts_created', models.ManyToManyField(related_name='created_by_transaction', to='database.blockchainaddress')),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_from', related_query_name='%(app_label)s_%(class)ss_from', to='database.blockchainaddress')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_to', related_query_name='%(app_label)s_%(class)ss_to', to='database.blockchainaddress')),
            ],
            options={
                'db_table': 'blockchain_transactions',
            },
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('blockchainaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.blockchainaddress')),
                ('name', models.CharField(max_length=200, null=True)),
                ('abi', models.JSONField()),
            ],
            options={
                'db_table': 'blockchain_contracts',
            },
            bases=('database.blockchainaddress',),
        ),
        migrations.RemoveField(
            model_name='factorycontracttransaction',
            name='contracts_created',
        ),
        migrations.RemoveField(
            model_name='factorycontracttransaction',
            name='factory_contract',
        ),
        migrations.RemoveField(
            model_name='factorycontracttransaction',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='factorycontracttransaction',
            name='to_address',
        ),
        migrations.AddField(
            model_name='dao',
            name='deepdao',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='daoframework',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='daoframework',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='dao',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='dao',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='DaoFactoryContract',
            fields=[
                ('smartcontract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.smartcontract')),
                ('version', models.CharField(max_length=200, null=True)),
                ('dao_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='database.daoframework')),
            ],
            options={
                'db_table': 'dao_factory_contracts',
            },
            bases=('database.smartcontract',),
        ),
        migrations.CreateModel(
            name='DaoFactoryContractTransaction',
            fields=[
                ('blockchaintransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.blockchaintransaction')),
                ('factory_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='database.daofactorycontract')),
            ],
            options={
                'db_table': 'dao_factory_transactions',
            },
            bases=('database.blockchaintransaction',),
        ),
        migrations.DeleteModel(
            name='FactoryContract',
        ),
        migrations.DeleteModel(
            name='FactoryContractTransaction',
        ),
        migrations.AddField(
            model_name='dao',
            name='created_by_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)ss_created', to='database.daofactorycontracttransaction'),
        ),
    ]
