# Generated by Django 4.0.3 on 2022-04-21 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_contract_daofactory_contract_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.CharField(default='0', max_length=30, primary_key=True, serialize=False)),
                ('text', models.CharField(default='', max_length=280)),
                ('created_at', models.DateField()),
                ('metrics_impression_count', models.PositiveSmallIntegerField()),
                ('metrics_like_count', models.PositiveSmallIntegerField()),
                ('metrics_reply_count', models.PositiveSmallIntegerField()),
                ('metrics_retweet_count', models.PositiveSmallIntegerField()),
                ('metrics_url_link_clicks', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'tweets',
            },
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.CharField(default='0', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=15)),
                ('created_at', models.DateField()),
                ('description', models.CharField(default='', max_length=500)),
                ('metrics_tweet_count', models.PositiveIntegerField()),
                ('metrics_followers_count', models.PositiveIntegerField()),
                ('url', models.URLField(null=True)),
            ],
            options={
                'db_table': 'twitter_accounts',
            },
        ),
        migrations.AddField(
            model_name='dao',
            name='twitter_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='dao',
            name='twitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='database.twitteraccount'),
        ),
    ]
