# Generated by Django 4.0.3 on 2022-04-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_tweet_twitteraccount_dao_twitter_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='metrics_impression_count',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='metrics_like_count',
            new_name='reply_count',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='metrics_reply_count',
            new_name='retweet_count',
        ),
        migrations.RenameField(
            model_name='twitteraccount',
            old_name='metrics_followers_count',
            new_name='followers_count',
        ),
        migrations.RenameField(
            model_name='twitteraccount',
            old_name='metrics_tweet_count',
            new_name='tweet_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='metrics_retweet_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='metrics_url_link_clicks',
        ),
        migrations.AddField(
            model_name='tweet',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='twitteraccount',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
