# Generated by Django 4.0.3 on 2022-04-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_blockchaintransaction_smartcontract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='articulated_trace',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='contracts_created',
            field=models.ManyToManyField(null=True, related_name='created_by_transaction', to='database.blockchainaddress'),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='abi',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
