# Generated by Django 4.0.3 on 2022-04-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_blockchaintransaction_articulated_trace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='contracts_created',
            field=models.ManyToManyField(related_name='created_by_transaction', to='database.blockchainaddress'),
        ),
    ]
