# Generated by Django 4.0.3 on 2022-04-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_blockchaintransaction_contracts_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchaintransaction',
            old_name='block',
            new_name='block_number',
        ),
        migrations.AlterField(
            model_name='daofactorycontract',
            name='version',
            field=models.CharField(default='not specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='daoframework',
            name='name',
            field=models.CharField(default='not specified', max_length=200),
        ),
    ]
