# Generated by Django 4.0.3 on 2022-04-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_tweet_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
