# Generated by Django 4.0.3 on 2022-04-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_tweet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
