# Generated by Django 4.0.3 on 2022-04-23 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_tweet_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtlMonitor',
            fields=[
                ('name', models.CharField(default='test', max_length=20, primary_key=True, serialize=False)),
                ('last_scrape_time', models.DateTimeField()),
                ('last_scrape_block', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'etl_monitors',
            },
        ),
        migrations.AddField(
            model_name='daofactory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='daofactory',
            name='contract_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.blockchainaddress'),
        ),
    ]
