# Generated by Django 4.0.3 on 2022-04-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_etlmonitor_daofactory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etlmonitor',
            name='last_scrape_time',
            field=models.DateTimeField(null=True),
        ),
    ]
