# Generated by Django 4.0.3 on 2022-04-24 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_etlmonitor_last_scrape_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchaintransaction',
            name='error',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='function_inputs',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='function_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='function_outpus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='BlockchainTransactionTrace',
            fields=[
                ('id', models.CharField(default='0.0.0', max_length=50, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('error', models.CharField(max_length=20, null=True)),
                ('compressed_trace', models.CharField(max_length=1000, null=True)),
                ('output', models.CharField(max_length=1000, null=True)),
                ('delegates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegate_for_trace', to='database.blockchainaddress')),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces_from', to='database.blockchainaddress')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces_to', to='database.blockchainaddress')),
            ],
            options={
                'db_table': 'blockchain_transaction_traces',
            },
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='traces',
            field=models.ManyToManyField(related_name='originating_from_transaction', to='database.blockchaintransactiontrace'),
        ),
    ]
