# Generated by Django 4.0.3 on 2022-04-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_blockchaintransaction_error_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blockchaintransactiontrace',
            table='blockchain_traces',
        ),
    ]
