# Generated by Django 4.0.3 on 2022-04-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_rename_function_inputs_blockchaintransaction_call_inputs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daofactory',
            name='dao_creation_functions_str',
            field=models.CharField(default='', max_length=50),
        ),
    ]
