# Generated by Django 4.0.3 on 2022-04-25 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_daofactory_dao_creation_functions_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchainaddress',
            name='contract_abi',
        ),
        migrations.CreateModel(
            name='ContractAbi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_url', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=20)),
                ('inputs', models.JSONField(default=dict, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abis', to='database.blockchainaddress')),
            ],
            options={
                'db_table': 'contract_abis',
            },
        ),
        migrations.AddConstraint(
            model_name='contractabi',
            constraint=models.CheckConstraint(check=models.Q(('address__isnull', True), ('contract_url__isnull', True), _negated=True), name='database_contractabi_address_or_contract_url'),
        ),
    ]
