# Generated by Django 4.0.3 on 2022-04-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_remove_blockchainaddress_contract_abi_contractabi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dao',
            name='id',
            field=models.CharField(default='', max_length=25, primary_key=True, serialize=False),
        ),
    ]
