# Generated by Django 4.0.3 on 2022-04-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_alter_dao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(default='', max_length=400),
        ),
    ]
