# Generated by Django 4.0.3 on 2022-04-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_tweet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='urls',
            field=models.CharField(default='', max_length=300),
        ),
    ]
