# Generated by Django 4.0.3 on 2022-04-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_tweet_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='reply_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweet_count',
            field=models.PositiveIntegerField(),
        ),
    ]
