# Generated by Django 4.0.3 on 2022-04-26 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_alter_tweet_reply_count_alter_tweet_retweet_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dao',
            name='twitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dao', to='database.twitteraccount'),
        ),
    ]
