# Generated by Django 4.0.3 on 2022-04-26 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_alter_dao_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepdaoAddress',
            fields=[
                ('id', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(null=True)),
                ('organization_name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deepdao_info', to='database.blockchainaddress')),
            ],
            options={
                'db_table': 'deepdao_addresses',
            },
        ),
        migrations.AddField(
            model_name='dao',
            name='deepdao_addresses',
            field=models.ManyToManyField(related_name='belongs_to_dao', to='database.deepdaoaddress'),
        ),
    ]
