# Generated by Django 4.0.3 on 2022-04-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_deepdaoaddress_dao_deepdao_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='governance_topics',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tweet',
            name='is_governance_related',
            field=models.BooleanField(default=False),
        ),
    ]
