# Generated by Django 4.0.3 on 2022-04-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_tweet_governance_topics_tweet_is_governance_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='governance_topics',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='is_governance_related',
        ),
    ]
