# Generated by Django 4.0.3 on 2022-04-26 14:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_remove_tweet_governance_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='governance_topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), null=True, size=None),
        ),
        migrations.AddField(
            model_name='tweet',
            name='is_governance_related',
            field=models.BooleanField(default=False),
        ),
    ]
