# Generated by Django 4.0.3 on 2022-04-27 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_tweet_governance_topics_tweet_is_governance_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='from_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_from', to='database.blockchainaddress'),
        ),
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='to_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_to', to='database.blockchainaddress'),
        ),
        migrations.AlterField(
            model_name='blockchaintransactionlog',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_from', to='database.blockchainaddress'),
        ),
        migrations.AlterField(
            model_name='blockchaintransactionlog',
            name='compressed_log',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blockchaintransactiontrace',
            name='compressed_trace',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blockchaintransactiontrace',
            name='delegate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegate_for_trace', to='database.blockchainaddress'),
        ),
        migrations.AlterField(
            model_name='blockchaintransactiontrace',
            name='from_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces_from', to='database.blockchainaddress'),
        ),
        migrations.AlterField(
            model_name='blockchaintransactiontrace',
            name='to_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces_to', to='database.blockchainaddress'),
        ),
        migrations.AlterField(
            model_name='contractabi',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abis', to='database.blockchainaddress'),
        ),
        migrations.AlterField(
            model_name='daofactory',
            name='contract_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.blockchainaddress'),
        ),
        migrations.AlterField(
            model_name='daofactory',
            name='dao_framework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factories', to='database.daoframework'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='DaoSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=50, null=True)),
                ('dao_name_raw', models.CharField(max_length=50, null=True)),
                ('dao_name_clean', models.CharField(max_length=50, null=True)),
                ('q1', models.PositiveSmallIntegerField()),
                ('q2', models.PositiveSmallIntegerField()),
                ('q3', models.PositiveSmallIntegerField()),
                ('q4', models.PositiveSmallIntegerField()),
                ('q5', models.PositiveSmallIntegerField()),
                ('comments', models.TextField(null=True)),
                ('dao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='database.dao')),
            ],
            options={
                'db_table': 'survey_responses',
                'unique_together': {('timestamp', 'dao_name_clean')},
            },
        ),
    ]
