# Generated by Django 4.0.3 on 2022-04-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_blockchaintransaction_addresses_involved'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainaddress',
            name='chifra_list_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
