# Generated by Django 4.0.3 on 2022-05-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_blockchainaddress_chifra_list_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainaddress',
            name='record_modified_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
